### ISSUE TITLE
Rework SetFont(n int)

### ISSUE THREAD

**Issue by CptPie** [joeyak/hoin-printer#2]
How about actual values (a 2 value const) for the possible values instead of an plain int

https://github.com/joeyak/hoin-printer/blob/d948be996d30a50433a1afd15c6e044cc8a28e36/printer.go#L378

something like 
```go

type Font int

const (
   fontA Font = iota
   fontB
)
```
That way the equality check for 0 or 1 is handled cleaner imho

**Comment by joeyak** [comment]
Handled in e35cc8d81bfed2c65fcf5e161bf0d83fe06ff773
